spring:
  mvc:
    view:
      suffix: .html
  datasource:
    username: root
    password: woshih
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  type-aliases-package: com.example.hong.pojo
  mapper-locations: classpath:mapper/*.xml

