spring:
  datasource:
    username: root
    password: woshih
    url: jdbc:mysql://localhost:3306/s_t?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.hong.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml